title: 'Next'
email: ''
description: ''
tel: ''
company: 'hubstack'

baseurl: '../..' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com or http://[yourusername].github.io

# Build settings
exclude: ['node_modules', 'gulpfile.js', 'package.json', 'package-lock.json']
plugins:
  - jekyll-minifier
jekyll-minifier:
  exclude: ['assets/css/*.css', '*.min.*']
